services:
  db:
    image: postgres
    container_name: myspace-db
    restart: always
    ports:
      - 5438:5432
    env_file:
      - './.env.local'
    volumes:
      - myspace-db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: myspace-adminer
    restart: always
    ports:
      - 8089:8080
    environment:
      - ADMINER_DESIGN=dracula
volumes:
  myspace-db-data:
