import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import MainNav from './MainNav';
import AuthProvider from './AuthProvider';
import Link from 'next/link';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <AuthProvider session={session}>
      <html lang='en'>
        <head>
          <link rel='shortcut icon' href='favicon.ico' type='image/x-icon' />
        </head>
        <body className={inter.className}>
          <div className='container'>
            <MainNav />
            {children}

            <footer>
              <ul>
                <li>
                  <Link href={'/about'}>About</Link>
                </li>{' '}
                |
                <li>
                  <Link
                    target='_blank'
                    referrerPolicy='no-referrer'
                    href={'https://www.youtube.com/@thetalkingdev'}>
                    YouTube
                  </Link>
                </li>{' '}
                |
                <li>
                  <Link href={'/login'}>Source Code</Link>
                </li>{' '}
                |
                <li>
                  <Link
                    target='_blank'
                    referrerPolicy='no-referrer'
                    href={'https://nextjs.org'}>
                    NextJS Docs
                  </Link>
                </li>
              </ul>
            </footer>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
